name: advanced event action workflow  

on: 
    push:  
    issues:
      - opened
      - labeled
    fork:
jobs:  
  
  test:
    runs-on: ubuntu-latest  
    
    steps:  
      - name: Run Test  
        run: |  
          echo github.event_name: "${{ github.event_name }}" 
          echo Run Test  
  
  